### ISSUE TITLE
Communicating between cluster

### ISSUE THREAD

**Issue by PiyushRamuka** [uqee/sticky-cluster#10]
Hi - 

What is the best way to communicate between worker using sticky-cluster? It would be very helpful if you can post an example for same. Thanks!

-Piyush

**Comment by uqee** [comment]
It depends on your use case (e.g. worker-worker or master-worker communication), but generally speaking you should follow 4 simple steps:

1. Detect current process type by calling [`cluster.isMaster`](https://nodejs.org/api/cluster.html#cluster_cluster_ismaster) or [`cluster.isWorker`](https://nodejs.org/api/cluster.html#cluster_cluster_isworker).

2. Get currently running workers from the master process: [`cluster.workers`](https://nodejs.org/api/cluster.html#cluster_cluster_workers).

3. Register [`message`](https://nodejs.org/api/cluster.html#cluster_event_message) event listeners.

3. Send messages via [`worker.send`](https://nodejs.org/api/cluster.html#cluster_worker_send_message_sendhandle_callback).

For more detailed info and examples take a look at the node's [cluster documentation](https://nodejs.org/api/cluster.html).
