### ISSUE TITLE
Getting module 'string-hash' error while executing example 

### ISSUE THREAD

**Issue by abhijitroy-mit** [uqee/sticky-cluster#14]
Hi,

I was exploring your module but unable to proceed as the example provided is not working. Getting Error: Cannot find module 'string-hash'. I tried installing it using npm install, but it didn't work. Below is the error details...

`export NODE_ENV=development; node index.js`

`1482731086375  MASTER  start..`
`module.js:457`
`    throw err;`
`    ^`

`Error: Cannot find module 'string-hash'`
`    at Function.Module._resolveFilename (module.js:455:15)`
`    at Function.Module._load (module.js:403:25)`
`    at Module.require (module.js:483:17)`
`    at require (internal/module.js:20:19)`
`    at serverCreate (/Users/abhijitroy/Documents/Working/tmp/sticky-cluster/lib/master.js:10:16)`
`    at serverStart (/Users/abhijitroy/Documents/Working/tmp/sticky-cluster/lib/master.js:19:22)`
`    at Object.start (/Users/abhijitroy/Documents/Working/tmp/sticky-cluster/lib/master.js:43:5)`
`    at module.exports (/Users/abhijitroy/Documents/Working/tmp/sticky-cluster/lib/index.js:19:32)`
`    at Object.<anonymous> (/Users/abhijitroy/Documents/Working/tmp/sticky-cluster/example/index.js:58:1)`
`    at Module._compile (module.js:556:32)`

`npm ERR! Darwin 16.3.0`
`npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"`
`npm ERR! node v6.4.0`
`npm ERR! npm  v3.10.7`
`npm ERR! code ELIFECYCLE`
`npm ERR! sticky-cluster-example@ start: `export NODE_ENV=development; node index.js`
`npm ERR! Exit status 1`
`npm ERR! `
`npm ERR! Failed at the sticky-cluster-example@ start script "export NODE_ENV=development; node index.js".`
`npm ERR! Make sure you have the latest version of node.js and npm installed.`
`npm ERR! If you do, this is most likely a problem with the sticky-cluster-example package,`
`npm ERR! not with npm itself.`
`npm ERR! Tell the author that this fails on your system:`
`npm ERR!     export NODE_ENV=development; node index.js`
`npm ERR! You can get information on how to open an issue for this project with:`
`npm ERR!     npm bugs sticky-cluster-example`
`npm ERR! Or if that isn't available, you can get their info via:`
`npm ERR!     npm owner ls sticky-cluster-example`
`npm ERR! There is likely additional logging output above.`

`npm ERR! Please include the following file with any support request:`
`npm ERR!     /Users/abhijitroy/Documents/Working/tmp/sticky-cluster/example/npm-debug.log`

**Comment by uqee** [comment]
Didn't you forget to run `npm install` in both the `example` and root folders?

**Comment by abhijitroy-mit** [comment]
Yes, I missed to run `npm install` for the application folder and hence it was giving this error. Thanks, it worked.
