### ISSUE TITLE
yarn add sticky-cluster errors.

### ISSUE THREAD

**Issue by arden** [uqee/sticky-cluster#15]
arden-2:TujiaoSocketServer arden$ yarn add sticky-cluster
yarn add v0.20.3
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
error sticky-cluster@0.3.0: The engine "node" is incompatible with this module. Expected version "^4.4.0".
error Found incompatible module
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by uqee** [comment]
Fixed.
