### ISSUE TITLE
how to use when node server behind Haproxy

### ISSUE THREAD

**Issue by ptqlc** [uqee/sticky-cluster#16]
when node server behind Haproxy, the module consider all clients connection from the proxy, so all clients are connected to one worker.
how to solve the problem, make clients connect to different workers?

Thank you

**Comment by uqee** [comment]
You could set your proxy to transparent mode.
Look at the example [here](http://www.loadbalancer.org/blog/setting-up-haproxy-with-transparent-mode-on-centos-6-x):
> Transparent mode with HAProxy allows you to see the IP Address of the clients computer while still having a high availability service using HAProxy.

**Comment by ptqlc** [comment]
thanks

发自我的 iPhone

在 2017年4月21日，下午3:19，Denis Zhbankov <notifications@github.com<mailto:notifications@github.com>> 写道：


You could set your proxy to transparent mode.
Look at the example here<http://www.loadbalancer.org/blog/setting-up-haproxy-with-transparent-mode-on-centos-6-x>:

Transparent mode with HAProxy allows you to see the IP Address of the clients computer while still having a high availability service using HAProxy.
