### ISSUE TITLE
Any example integrating with socket.io?

### ISSUE THREAD

**Issue by fott1** [uqee/sticky-cluster#17]
I am actually trying ta make a socket.io app integrate with `sticky-cluster`. Although i am having trouble, because my server is not listening the main requests on the given port. Is there any a bit more detailed example on applying the lib?

**Comment by uqee** [comment]
Hi, @fott1 !
Look at the [get started section](https://github.com/uqee/sticky-cluster#get-started) and just add:
```javascript
const io = require('socket.io')(server);
// do something with io here
```
in the
```javascript
// configure an app
```
section.

**Comment by fott1** [comment]
Cool @uqee, i will give it a try. So io and http will listen to the same port?

**Comment by uqee** [comment]
Yes. Let me know if it helps, I'll close the issue then.
