### ISSUE TITLE
HTTPS/TLS

### ISSUE THREAD

**Issue by gboysko** [uqee/sticky-cluster#19]
Should this module work when the Server is using HTTPS/TLS?

**Comment by uqee** [comment]
Currently it reads client's IP address from [`connection.remoteAddress`](https://nodejs.org/api/net.html#net_socket_remoteaddress). It should also work in HTTPS. If it doesn't though, just submit an issue, I'll fix it )

**Comment by gboysko** [comment]
Thanks. I thought that the proxy server you create in the master process would need to be HTTPS/TLS as well, but perhaps I'm wrong. I haven't tried it yet.

**Comment by uqee** [comment]
The master process creates a TCP proxy (lower level) instead of HTTP, so it should handle HTTPS too, I guess.
