### ISSUE TITLE
Request for better shutdown handling?

### ISSUE THREAD

**Issue by gboysko** [uqee/sticky-cluster#22]
Has anyone reported problems with shutdown? That is, when a graceful shutdown is initiated (via `SIGINT`) has anyone reported the server simply not stopping? 

I am seeing this behavior and I suspect the issue is related to open connections. This socket.io [issue](https://github.com/socketio/socket.io/issues/1602) seems to reflect this problem.

I'm wondering whether we can implement this functionality in this module. This could address the graceful shutdown problem.

**Comment by uqee** [comment]
Yes, when a master process receives `SIGINT` it stops accepting new connections, but [keeps existing](https://nodejs.org/api/net.html#net_server_close_callback). Once they finished, it shuts down all workers and exits.

Another strategy could be implemented too, e.g. for a `SIGTERM` signal. It can forcefully kill its workers no matter what. I'm not sure if it's the right thing to do though. If you don't care, couldn't you just `SIGKILL`?

**Comment by gboysko** [comment]
I don't believe that you can trap `SIGTERM` in Node.js. I could be wrong. I implemented a wrapper class around this module that does the following:

1. At startup, each worker registers a handler for a shutdown message.
    1. In addition, I add my own handler for the `sticky-cluster:connection` message by recording the connection in a map (and releasing the entry when the connection closes).
1. Master process traps `SIGINT`. Sends a specific "shutdown" message to each worker.
    1. When each child receives the "shutdown" message, it destroys each of the remaining connections in its connection map.
1. Similarly, I register a "hard shutdown" timeout (set for 60s) that runs if the graceful shutdown has not yet finished.
    1. This simply sends `SIGTERM` to each worker process and then exits (with status code 1).

This has worked for me and I think it would be great if we integrated these changes directly into the module directly.

**Comment by uqee** [comment]
How often it still needs a "hard shutdown" in your experience? And what exactly did you achieve once you had implemented this logic, compared to a forceful killing?

**Comment by gboysko** [comment]
I haven't seen a "hard shutdown" happen in my limited testing, but I've only been testing with a few CPU cores. Perhaps with more (8+), there might be some lag, but its only conjecture.

What do we achieve by a graceful shutdown? It allows us to inform service monitoring software that our shutdown was planned and not accidental. We have software that monitors the life of the process and tries to restart a process that dies accidentally. Normal (graceful) shutdowns should not trigger an automatic restart.

In general, a process can perform cleanup or other tasks normally associated with a normal shutdown.

**Comment by gboysko** [comment]
Would you be open to accepting this change if it was supplied as a Pull Request?

**Comment by uqee** [comment]
Would love to. I definitely don't have much time for it now :( Just please try to reduce any additional overhead as much as possible to preserve the main advantage of this project: speed.

**Comment by gboysko** [comment]
I'll see if we can't submit a PR in the next week or so.

**Comment by xiaolongguan** [comment]
Hello @uqee , I am working with @gboysko on the graceful shutdown. The code changes are ready and I have tested it in my Mac & Windows & Linux machine. I'd like to make a pull request for you to review our code changes, but it seems I don't have the permission to create my own branch based on the `dev` branch.  Could you grant @gboysko or me the permission to make the PR? Thanks.

**Comment by xiaolongguan** [comment]
Hi @uqee , I am working with @gboysko on the graceful shutdown and made a pull request: https://github.com/uqee/sticky-cluster/pull/25, could you please help review it? Thanks.
