### ISSUE TITLE
ERROR: uncaughtException: write EIO

### ISSUE THREAD

**Issue by sraja83** [uqee/sticky-cluster#23]
I am getting uncaught exception, attached is my code for starting the server. If my server is idle for 20 to 30 mins, after that when i try to load any url i am getting 404 and i got below exception

`[PID
 : 3575 AT : 30-08-2017 13:53:45.889] ERROR: uncaughtException: write EIO
STACK TRACE
Error: write EIO,    at exports._errnoException (util.js:1018:11),    at WriteWrap.afterWrite (net.js:800:14)
{ date: 'Wed Aug 30 2017 13:53:45 GMT+0000 (UTC)',
  process: 
   { pid: 3575,
     uid: 0,
     gid: 0,
     cwd: '/wifimx/runtime/proximity-runtime',
     execPath: '/usr/bin/node',
     version: 'v6.11.1',
     argv: 
      [ '/usr/bin/node',
        '/wifimx/runtime/proximity-runtime/runtime.js' ],
     memoryUsage: 
      { rss: 97402880,
        heapTotal: 70520832,
        heapUsed: 61763448,
        external: 18027708 } },
  os: { loadavg: [ 0, 0.01513671875, 0 ], uptime: 25976 },
  trace: 
   [ { column: 11,
       file: 'util.js',
       function: 'exports._errnoException',
       line: 1018,
       method: '_errnoException',
       native: false },
     { column: 14,
       file: 'net.js',
       function: 'WriteWrap.afterWrite',
       line: 800,
       method: 'afterWrite',
       native: false } ] }`

[server.txt](https://github.com/uqee/sticky-cluster/files/1266761/server.txt)
please let me know how to solve this issue.

**Comment by uqee** [comment]
Looks quite similar to the #24
