### ISSUE TITLE
Can't make it work with pm2+socket.io 2

### ISSUE THREAD

**Issue by qiulang** [uqee/sticky-cluster#26]
Hi,

Can you provide some example to show how to use it with pm2 cluster and socket.io ? I just can't make it work even for the simplest socket.io example.

Thanks!

**Comment by uqee** [comment]
As `pm2` already has some cluster functionality, it interferes with `sticky-cluster`. I don't think it is the best idea to combine them.. Read [this](https://github.com/Unitech/pm2/issues/389#issuecomment-231420126) and [that](https://github.com/Unitech/PM2/issues/1510#issuecomment-337008088), may be it will help.

**Comment by qiulang** [comment]
Thanks. I kinda figure that out after failing to do it many times.

**Comment by uqee** [comment]
You're welcome
