### ISSUE TITLE
When start it from vs-code, socket.io connection will fail

### ISSUE THREAD

**Issue by qiulang** [uqee/sticky-cluster#27]
Hi,  I don't believe it is a bug. I just want to if you have any experience with vs-code.
So I am continuing to test 'sticky-cluster' and found that if I start node from vs-code the socket.io connection will fail (of course if I don't use stick-session it won't).

From vs-code debug window, I **DID** find anything suspicious,

Debugging with inspector protocol because Node.js v8.6.0 was detected.
node --inspect-brk=3149 app.js 
Debugger listening on ws://127.0.0.1:3149/b427678b-2d45-41a4-9043-3f2cf3da4b9f
Debugger attached.
MASTER  start..
MASTER  ..started at port 3000
WORKERS  start..
WORKER #1  ..started
...
**MASTER  conn from ::ffff:10.0.0.117 goes to worker #1**
MASTER  conn from ::1 goes to worker #4
...

If I start it from terminal, after   MASTER  conn from ::ffff:10.0.0.117 goes to worker #1
There will be another message  **WORKER #1  got conn from ::ffff:10.0.0.117**
Then the connection will succeed.

So any idea what was wrong here?

Thanks!

**Comment by uqee** [comment]
At first, I would make sure workers really did start by running `ps` command in terminal. If they did, may be the debugger somehow breaks IPC communication. Then I would make a little debugging:

Go to the [line](https://github.com/uqee/sticky-cluster/blob/master/lib/workers.js#L59): save its return value and also add a callback parameter as described [here](https://nodejs.org/api/child_process.html#child_process_subprocess_send_message_sendhandle_options_callback).

If the returned value equals `false`, then the IPC channel has closed or the backlog of unsent messages exceeds a threshold that makes it unwise to send more.

If the callback receives an non-null argument, then it's an `Error` object, which should indicate what happened.
