### ISSUE TITLE
Need to handle server startup errors

### ISSUE THREAD

**Issue by gboysko** [uqee/sticky-cluster#28]
Right now, if the port specified is already in use, an unhandled error (`Error: listen EADDRINUSE`) will be raised and the system will fail unexpectedly.

We would like some way to handle unexpected errors like these and trigger our own shutdown process. Here's how it could work:

1. Allow the caller to specify a callback
1. Attach the handler/callback fn to the `net.Server.error` event on the `serverInstance` created in `master.js`. 

Thoughts?
Glenn

**Comment by uqee** [comment]
Why not
