### ISSUE TITLE
How does it load balance requests that come via corporate proxy

### ISSUE THREAD

**Issue by techwizardg** [uqee/sticky-cluster#32]
If we use IP Address alone for hash, how would load balancing work as all requests would go to the same worker as the IP Address behind a corporate proxy would be same. Should we need to use along with IP Address , port for hashing? Any thoughts on the same

**Comment by uqee** [comment]
Yes, it uses client's IP address to choose a worker: if it's the same, then every request would land to the same worker. Browsers can choose arbitrary ports for outgoing requests, so if we also consider remote port when choosing a worker, it wouldn't be guaranteed that the same browser will hit the same worker again.
