### ISSUE TITLE
Restrict port numbers used in launched workers?

### ISSUE THREAD

**Issue by gboysko** [uqee/sticky-cluster#37]
Has anyone ever asked that the child processes that `sticky-cluster` creates use ports in a desired range? Or that they don't use ports from a specific "reserved" list? 

We have a requirement like this and wanted to see how this can be accomplished. Right now, the OS allocates a port from the unused list.

The only solution I can consider is either:

1. Allocate the ports from a specific range supplied in the configuration, OR
1. Check if a randomly selected port falls into the "DO NOT USE" list, and if so, try to randomly select a different one

It seems like option #1 is more likely (doable), though it has it's own challenges (what if those ports are already in use). Option #2 also has it's challenges (what if after selecting an undesirable port, the process re-spawns and selects the same undesirable port?). 

I'd be glad to submit a PR, but just looking for guidance from the community.

**Comment by uqee** [comment]
https://github.com/kessler/find-port may be?

**Comment by gboysko** [comment]
Thanks @uqee. Do you think that this is a worth while change? We are still considering whether it is necessary for us or not.

**Comment by uqee** [comment]
sorry for the delay ( i'm a fan of modularized approach, so in my opinion it's better to stay within the limits and not merge every possible functionality
