### ISSUE TITLE
The module not working with proxy_pass

### ISSUE THREAD

**Issue by salih3451** [uqee/sticky-cluster#39]
I made the nginx configuration like this:
` proxy_set_header Host $http_host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
`
In the debug mode, i see WORKER #3 get conn from "ip_address"
I connected from many computers on the same server, but still getting same "ip_address" ( server's ). Because of this problem, cluster shows all clients has same ip. How do i get the client's real ip address?

**Comment by uqee** [comment]
Hi, @salih3451 
Unfortunately, it's not possible, because of https://github.com/uqee/sticky-cluster/issues/18#issuecomment-303365618. The thread also has a link to SO answer with a hint for pure-Nginx configuration.
