### ISSUE TITLE
Proxy issue on new connection

### ISSUE THREAD

**Issue by tienlx93** [uqee/sticky-cluster#4]
On lib/master.js:15. Due to some proxy issue, connection.remoteAddress can be null/undefined. So function hash will lead to fatal error (server throw error and stop)

Please help me on this issue

**Comment by uqee** [comment]
Hi, @tienlx93 !
If you're behind an additional proxy, chances are, the valid IP is in the `X-Forwarded-For` header, but master process does not even start reading a socket to get this value, so it's a bit of a problem here. Does that happen all the time or in some rare cases only (like in that [SO question](http://stackoverflow.com/questions/35633437/node-js-net-module-remoteaddress-is-undefined))? In the latter case we can add a quick fix: say, give all these strange connections to the first worker. Would it be acceptable for you?

**Comment by tienlx93** [comment]
Thanks for your response.
Only in rare cases, the IP is invalid.
So please give a option to choose whether give strange connection to first worker, or return a error HTTP status to user for us for later uses.
Thanks.
