### ISSUE TITLE
restart program

### ISSUE THREAD

**Issue by RezaErfani67** [uqee/sticky-cluster#41]
can i re run function for restart program?

**Comment by uqee** [comment]
of course, just like any other server, e.g. send it a SIGINT signal (Ctrl+C)

**Comment by RezaErfani67** [comment]
can i have sample code?
how to send and receive signal?
```javascript
require('sticky-cluster')(
  function (callback) {
    var http = require('http');
    var app = require('express')();
    var server = http.createServer(app);
    callback(server);
  process.on('SIGINT', function() {
                    process.exit(0);
                });
  },
  
  // options
  {
    concurrency: 10,
    port: 3000,
    debug: true,
    env: function (index) { return { stickycluster_worker_index: index }; }
  }
);
```

**Comment by uqee** [comment]
if you start the server from a terminal via `node your-app.js`, then you can terminate it simply with `Ctrl+C` combination. or you can send a signal via `kill` command, if a PID is known (it is, if you've actually forked the program from a different process, or it could be figured out with a `ps` command)

**Comment by RezaErfani67** [comment]
all of your description is ok...
but i want do that programmatically...
it can happen on router function to restart program

**Comment by uqee** [comment]
could you provide more details about your task and environment?

**Comment by RezaErfani67** [comment]
what can i do if one process die?
all clients that map their ip address to this process, are unusable.
note:
i work in windows

**Comment by uqee** [comment]
this process will be restarted automatically

**Comment by RezaErfani67** [comment]
seriously?! 
then if  one process goes to shutting down, recover itself?

**Comment by uqee** [comment]
yes, that's the whole point )

**Comment by RezaErfani67** [comment]
thanks a lot :)
