### ISSUE TITLE
random port in workers

### ISSUE THREAD

**Issue by gNull-ph** [uqee/sticky-cluster#42]
// start local server
    server.listen(0/* start on random port */, 'localhost' /* accept conn from this host only */);

why need to start on random port?? 
 stickyCluser(startFn,{
    concurrency: parseInt(require('os').cpus().length ),
    port: normalizePort(process.env.PORT || '8080'),
    debug: true,
    env: function(index) {
        return {stickycluster_worker_index: index};
    }
  })
why not  listen on port  8080??

**Comment by uqee** [comment]
because it's a client, not the master, who should actually accept connections from the outside world

**Comment by gNull-ph** [comment]
> because it's a client, not the master, who should actually accept connections from the outside world

beginner only.  thanks for response
