### ISSUE TITLE
Will I need use PM2 along with sticky-cluster to run forever nodejs

### ISSUE THREAD

**Issue by JamesStark-wasp** [uqee/sticky-cluster#44]
is there any necessity to run my Socket.io nodejs process using PM2?
If my server crash duet any error within code will sticky-cluster auto restart the process?
Can we use PM2 along with sticky-cluster? 

I am using 'socket.io-redis' module for clustering with redis Key Value memory cache mechanism to store Socket id of all connected users.

**Comment by uqee** [comment]
Hi, @JamesStark-wasp, thanks for reaching out! Unfortunately, I'm not an expert of `pm2`'s functionality to give a well thought recommendation. If you're interested in my guess, then I think that you definitely can start `sticky-cluster` based app with `pm2`, that way `pm2` will restart master process and `sticky-cluster` will restart child processes.

**Comment by JamesStark-wasp** [comment]
Thanks for your interest 

When I started sticky-cluster based app with [PM2 ](https://www.npmjs.com/package/pm2) using  `pm2 start api.js -i max `
command its not working client disconnected from socket.io immediately
