### ISSUE TITLE
Possible option for target worker

### ISSUE THREAD

**Issue by Jared-Sprague** [uqee/sticky-cluster#6]
Hello!
This module is so close to exactly what I need, with one exception.  I want to be able to specify which worker a connection ends up on based on a request header, not client IP. 

The use case is an "Invite a friend" scenario, where a game is running on multiple workers, and someone playing on one worker wants to invite a friend to come join the same server instance.   I could create a special link that would connect to the server with an 'X-target-worker: 1'  header that when the master sees it assigns the connection to that worker.  Any other in comming connections without that header, could just be round-robbined to workers.

Could this be a possible new mode?

**Comment by uqee** [comment]
Unfortunately, not. You want a master process to partially read the socket before passing it to a worker, therefore the latter wouldn't have any access to that part.

May be it's also possible in any way, but surely not within the current concept.

**Comment by Jared-Sprague** [comment]
But that master is already doing that, that's how it gets the remote address, from a header in the socket connection.   It would basically be exactly the same thing, just a different header.

Here is the concept in TOTAL psudo code:
master.js:

```
...
  function serverCreate () {
    var hash = require('string-hash');
    return require('net')
      .createServer({ pauseOnConnect: true }, function (connection) {

        IF MODE===IP
            var index = hash(connection.remoteAddress || '') % CONCURRENCY;
        ELSE IF MODE===WORKER_ID
            var index = hash(connection.headers.x_worker_id || '') % CONCURRENCY; 

        workers.entrust(index, connection);
      });
}
...
```

**Comment by uqee** [comment]
Yes, master gets the remote address from the socket (e.g. TCP), but not from the HTTP headers, it's another OSI layer, which is not being read at all. Master accepts connections with the `pauseOnConnect` option enabled. You can read about that option in the [Node's documentation](https://nodejs.org/api/net.html#net_net_createserver_options_connectionlistener):

> If `pauseOnConnect` is `true`, then the socket associated with each incoming connection will be paused, and no data will be read from its handle. This allows connections to be passed between processes without any data being read by the original process. To begin reading data from a paused socket, call `resume()`.

**Comment by uqee** [comment]
I don't quite get it why do you need to connect to the very same OS process as the person who invited you to join? Don't you use any shared data storage like Redis? You can transfer some initial data on `socketio.connect()` call to inform a server which playing room to use, for example. Am I missing something?

**Comment by Jared-Sprague** [comment]
Ah yes,  if we were doing that this wouldn't be a problem, but currently all our state is in the memory of the process.  we haven't had a need to store data outside of the node process, and are trying to keep it simple without adding another system.

**Comment by uqee** [comment]
Well, I guess we can close the issue now.
